---
title: "Course Introduction"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    css: "../css/note-style.css"
---

```{r, message=FALSE, echo=FALSE}
source("../funs/funs.R")
options(dsst.traceit = FALSE)
```

## Welcome!

Today we are going to do some housekeeping and course setup.

Today we are going to go through a few notes, which give a long-form version of
the posted syllabus and an outline of the course. We will then walk through
setting up the software we will be using throughout the semester.

## Website

All of the materials for the course can be found on the course website:

- https://statsmaths.github.io/dsst389-s22/index.html

Make sure to bookmark this somewhere easy to access. The page will remain
online indefinitely for your reference following the semester.

## Who am I?

- Taylor Arnold
- From New England: born in Maine, school in MA, ME, CT
- Moved to Richmond in 2016
- Faculty in Data Science and Linguistics
- Research on large text and image datasets in linguistics and cultural studies
- I apply and develop corpus-based techniques to study how messages are
communicated through texts and visual media
- Lots of industry experience in data science and predictive modelling:
  - IBM (Healthcare)
  - Travelers (Insurance)
  - DARPA (social media)
  - AT&T (location analytics)
  - Telperian (pharmaceuticals)

## What is machine learning?

- Machine Learning vs Statistical Learning: different histories but the same thing
- Machine Learning (ML) is a branch of artificial intelligence
- Uses data to create models
- Methods mostly fall into three groups:
  - **Supervised Learning**: detect patterns in order to make predictions about new data
  - **Unsupervised Learning**: detect patterns in order to organize and structure data
  - **Reinforcement Learning**: detect patterns in order to make complex decisions
- These are not disjoint areas, though, and many tasks require a mixture of methods.

## Machine learning examples?

Here are some examples of ML tasks. They are organized by the canonical type of
machine learning that each is usually associated with, though the optimal approach
may involve a mixture of methods.

- **Supervised Learning**
  - Predict the sale price of a house based on its size and location.
  - Predict whether an email message should be put into a user's spam box.
  - Find and identify all the faces found in a video feed.
- **Unsupervised Learning**
  - Cluster a collection of news paper articles by themes.
  - Find and recommend similar products to users on a digital commerce website.
  - Flag suspicious product reviews that should be manually investigated for fraud.
- **Reinforcement Learning**
  - Build an algorithm to play a game, such as checkers or chess, against a human.
  - Determine a way to optimally schedule elevators in a large office building.
  - Program a self-driving car.

## Teaching ML

There are three different approaches to teaching machine learning:

- **Mathematical Approach**: Focus on theoretical properties of various methods,
using the language of probability and numerical analysis.
- **Data Science Approach**: Focus on the application of ML
techniques in order to understand complex datasets.
- **CS/Engineering Approach**: Focus on implementation and performance of
ML techniques and algorithms.

This course is firmly situated in the **Data Science Approach**.

While we will cover techniques that are (mostly) applicable to a wide range of
applications, this semester will focus primarily on applications to large
collections of textual data.

## What will you learn from this course?

- understand the terminology of predictive and unsupervised ML methods
- how to apply a set of methods using the open-source R programming language
- how to use and understand a core set of general-purpose, interpretable ML methods
- how to use and understand several specific methods for working with textual data
- how to summarise and present the results of an exploratory analysis of data that
integrates ML methods

## What won't you (directly) learn?

- a laundry-list with dozens of ML methods
- theoretical justification/analysis of ML methods
- implementation details of ML methods
- a full introduction to R
- deep learning models

I have, however, tried to link to additional resources throughout the notes for
students interested in theoretical or implementation details.

## Things I expect from you

- regular attendance in class, arriving on time and being present for the full
class period
- make progress in class activities
- complete course form by the start of each class
- complete and present four course projects
- complete a two-page, end-of-semester, self assessment of what you have learned

## Class Groups

- Most of the work you complete for this course will be done in fixed groups
of 1-3 students.
  - Despite some challenges, I have found it to be the best approach to the
  material.
  - There will be plenty of time to work together during class; most
  of the other work should be possible to do asychronously.
  - Projects will be completed as a group. Your self-assessment will be
  submitted individually.
- I prefer that you all try to organise yourselves into groups.
  - Send me, by email, your group preferences by the end of the week.
  - I think groups of 2 are ideal, but working alone or in a group of 3
  is also possible.
  - I except groups to be remain fixed throughout the semester, but we can
  discuss changes if issues arise.

## Grades

- You will get a grade for each project out of 95 points.
- You will get a grade for the self-assessment out of 95 points.
- The project and course engagement grades are averaged.
- A letter grade is assigned as follows: A (93–95), A- (90–92), B+ (87–89),
B (83–86), B- (80–82), C+ (77–79), C (73–76), C- (70–72), and F (0–69).

## Project Format

The projects take the form of a short presentation. Rather than a textual
write-up, I want you to focus on producing clean, professional slides for the
presentation.

Here are the planned topics:

- IMDb movie reviews: predicting how many stars a movie review gives
- Amazon product reviews: predict the author of a review
- Yelp reviews: predict author of the review and cluster the corpus authors
- Wikipedia: detect themes in a subset of Wikipedia articles

## Office Hours

- I make a habit of staying after class as long as students have questions.
- Lot's of time in class for small questions.
- You can also always email questions.
  - I usually respond within one work day; if not, feel free to re-send.
  - If you are getting coding errors, it is easier for me if you send the text
  of your code (paste or attach the code), rather than a screen shot.
- Of course, I am also always happy to meet outside of class.
  - I find that when students want to meet, it is usually for a longer discussion.
  - No general fixed office hours. Just send me an email; usually can meet on
  Mondays and Wednesdays outside of class times.

## Frequently Asked Questions

- **Is there a textbook for the course?** No, we will be using my own notes and
references to other freely available resources.
- **Are there any exams?** No.
- **Is there a final exam?** No.
- **Can I switch sections?** No, due to our use of fixed groups.

## Course Software

We need to install three different components for this
semester:

1. The R Programming Language
2. The RStudio IDE
3. A set of R Packages and data

All of these components are open-source and available
for all modern operating systems. You may have trouble,
however, if you have an older OS and have not updated it
recently.

Even if you already have R installed, I suggest doing a
fresh update for the semester.

## Installing the R Language

To install R, go to https://cran.r-project.org/ and select
your operating system. Then:

- macOS => click on R-4.1.2.pkg and follow instructions
- Windows => click on base followed by "Download R"

For Linux, either install from source or use your favourite
package manager.

You need to install R before anything else, but we will
never actually open it directly. So feel free to remove and
shortcuts or links that are created during installation.

## Installing RStudio

To install RStudio, follow the following link and download either the
dmg (macOS) or exe (Windows):

- [https://www.rstudio.com/products/rstudio/download/#download](https://www.rstudio.com/products/rstudio/download/#download)

**Note**: On macOS, you need to drag the RStudio icon into your
Applications directory after downloading.

## Install R Packages

Finally, download and unzip the "materials.zip" file from the
class website. We will use this directory throughout the semester, so
put it somewhere you will remember it.

Then, open the setup.Rmd file in RStudio, and click the green play
buttons.

## For the Semester

You should plan on bringing a laptop with a working version of R,
RStudio, and all of the installed packages to each class meeting. If that
is or becomes an issue, just let me know and we will find a solution.

Note that if you are having computer issues, particularly during a project,
it is always possible to use the lab computers in Jepson as a
back-up. They have R and RStudio installed, but not all of the class R
packages. Simply start from Step 3 in these notes before getting
started.
